import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "../components/Header";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moera no Shokugeki",
  description: "Generated by GIOMA",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // // DEBUG: intercetto chiamate a localStorage sul server
  // if (typeof window === "undefined") {
  //   // Evita crash sostituendo localStorage sul server
  //   // e stampa nel terminale quando viene usato
  //   (globalThis as any).localStorage = {
  //     getItem: (...args: any[]) => {
  //       console.trace("⛔ getItem chiamato sul SERVER", args);
  //       return null;
  //     },
  //     setItem: (...args: any[]) => {
  //       console.trace("⛔ setItem chiamato sul SERVER", args);
  //     },
  //     removeItem: (...args: any[]) => {
  //       console.trace("⛔ removeItem chiamato sul SERVER", args);
  //     },
  //   };
  // }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <ReactQueryProvider>
          <main>{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
